root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/todo-app"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = ["*_test.go"]
  delay = 1000

