services:
  todo-app:
    container_name: todo-app
    build: .
    working_dir: /home/app
    ports:
      - "8765:8765"
      - "2345:2345"
    volumes:
      - type: bind
        source: .
        target: /home/app
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo
      DB_HOST: mysql
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - mysql
    command: ["air"]

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
