services:
  todo-app:
    container_name: todo-app
    build: .
    ports:
      - "8765:8765"
    volumes:
      - type: bind
        source: .
        target: /home/app
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
